package CadernoDeRegistro;
import DAO.DAO;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Felipe França Nogueira
 */
public class CadernoDeRegistro extends javax.swing.JFrame {
String root = "root";
String password = "felipe15";
DAO db = new DAO("jdbc:mysql://localhost:3306/registro",root,password); //Realiza conexão com o banco de dados Registro, recebendo o usuario e a senha do BD como Variáveis.
String dataBase = "registro";//Armazena nome do Banco de dados em uma Variável para que possa ser usado mais facilmente
String func;//Variável usada para armazenar nome do usuário após o login.
int i = 1;//Variável que aponta para o id do arquivo que o usuário estará vendo.

    /**
     * Inicializa a janela incial, Ocultando todas as janelas a não ser a de login.
     * Se não existir, irá criar a tabela arquivo.
     */
    public CadernoDeRegistro() {
        initComponents();
        negadoTxt.setVisible(false);
        voltarBtn.setVisible(false);
        menuBar.setVisible(false);
        menuPainel.setVisible(false);
        adcPainel.setVisible(false);
        verPainel.setVisible(false);
        usuarioMenu.setVisible(false);
        excluirArq.setVisible(false);
        db.update("create table if not exists arquivo"+
                                "(id int auto_increment primary key,"+
                                "funcionario varchar(80),"+
                                "data datetime,"+
                                "camera varchar(20),"+
                                "texto mediumtext);");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        verPainel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtVer = new javax.swing.JTextArea();
        proximoVer = new javax.swing.JButton();
        anteriorVer = new javax.swing.JButton();
        funcVer = new javax.swing.JLabel();
        dataVer = new javax.swing.JLabel();
        cameraVer = new javax.swing.JLabel();
        idVer = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        loginPainel = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        loginTxt = new javax.swing.JTextField();
        senhaLabel = new javax.swing.JLabel();
        acessarBtn = new javax.swing.JButton();
        senhaTxt = new javax.swing.JPasswordField();
        negadoTxt = new javax.swing.JLabel();
        voltarBtn = new javax.swing.JButton();
        menuPainel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        adcPainel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAdc = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cameraAdc = new javax.swing.JTextField();
        salvarBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        diaAdc = new javax.swing.JFormattedTextField();
        mesAdc = new javax.swing.JFormattedTextField();
        anoAdc = new javax.swing.JFormattedTextField();
        funcAdc = new javax.swing.JLabel();
        excPainel = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        sistemMenu = new javax.swing.JMenu();
        logoutMenu = new javax.swing.JMenuItem();
        arquivoMenu = new javax.swing.JMenu();
        novoArq = new javax.swing.JMenuItem();
        verAqr = new javax.swing.JMenuItem();
        excluirArq = new javax.swing.JMenuItem();
        usuarioMenu = new javax.swing.JMenu();
        addUser = new javax.swing.JMenuItem();
        excUser = new javax.swing.JMenuItem();
        editUser = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.white);
        setLocation(new java.awt.Point(300, 200));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Funcionario :");

        jLabel8.setText("Dia / Hora : ");

        jLabel9.setText("Camera :");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtVer.setEditable(false);
        txtVer.setColumns(20);
        txtVer.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        txtVer.setRows(5);
        jScrollPane2.setViewportView(txtVer);

        proximoVer.setText("Proximo ->");
        proximoVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximoVerActionPerformed(evt);
            }
        });

        anteriorVer.setText("<-Anterior");
        anteriorVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorVerActionPerformed(evt);
            }
        });

        funcVer.setText("jLabel10");

        dataVer.setText("jLabel11");

        cameraVer.setText("jLabel12");

        jLabel10.setText("---------------------------------------------------------------------------------------");

        jLabel11.setText("---------------------------------------------------------------------------------------");

        javax.swing.GroupLayout verPainelLayout = new javax.swing.GroupLayout(verPainel);
        verPainel.setLayout(verPainelLayout);
        verPainelLayout.setHorizontalGroup(
            verPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, verPainelLayout.createSequentialGroup()
                .addGroup(verPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(verPainelLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(anteriorVer)
                        .addGap(18, 18, 18)
                        .addComponent(proximoVer, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(idVer, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(verPainelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(verPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(verPainelLayout.createSequentialGroup()
                                .addGroup(verPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(verPainelLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cameraVer, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(verPainelLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(funcVer, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(verPainelLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dataVer, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 49, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        verPainelLayout.setVerticalGroup(
            verPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verPainelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(verPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(funcVer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(verPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataVer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(3, 3, 3)
                .addGroup(verPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cameraVer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(verPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idVer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(verPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(proximoVer)
                        .addComponent(anteriorVer)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(verPainel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 310));

        loginPainel.setForeground(new java.awt.Color(255, 255, 255));
        loginPainel.setInheritsPopupMenu(true);

        loginLabel.setText("Login :");

        senhaLabel.setText("Senha :");

        acessarBtn.setText("Acessar");
        acessarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acessarBtnActionPerformed(evt);
            }
        });

        negadoTxt.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        negadoTxt.setForeground(new java.awt.Color(153, 51, 0));
        negadoTxt.setText("Login/senha incorreta");

        voltarBtn.setText("Voltar");
        voltarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPainelLayout = new javax.swing.GroupLayout(loginPainel);
        loginPainel.setLayout(loginPainelLayout);
        loginPainelLayout.setHorizontalGroup(
            loginPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPainelLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(loginPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPainelLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(loginPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(voltarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acessarBtn)))
                    .addGroup(loginPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(loginPainelLayout.createSequentialGroup()
                            .addComponent(loginLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(loginTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(loginPainelLayout.createSequentialGroup()
                            .addComponent(senhaLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(loginPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(negadoTxt)
                                .addComponent(senhaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        loginPainelLayout.setVerticalGroup(
            loginPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPainelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(loginPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginLabel)
                    .addComponent(loginTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(negadoTxt)
                .addGap(13, 13, 13)
                .addGroup(loginPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhaLabel)
                    .addComponent(senhaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(acessarBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(voltarBtn)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getContentPane().add(loginPainel, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 39, 340, 250));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("Caderno de Registro");

        javax.swing.GroupLayout menuPainelLayout = new javax.swing.GroupLayout(menuPainel);
        menuPainel.setLayout(menuPainelLayout);
        menuPainelLayout.setHorizontalGroup(
            menuPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPainelLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel12)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        menuPainelLayout.setVerticalGroup(
            menuPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPainelLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel12)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        getContentPane().add(menuPainel, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 1, 420, 310));

        txtAdc.setColumns(20);
        txtAdc.setRows(5);
        jScrollPane1.setViewportView(txtAdc);

        jLabel1.setText("Camera :");

        jLabel3.setText("Dia :");

        jLabel4.setText("Funcionario :");

        salvarBtn.setText("Salvar");
        salvarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarBtnActionPerformed(evt);
            }
        });

        jLabel5.setText("/");

        jLabel6.setText("/");

        try {
            diaAdc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            mesAdc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            anoAdc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout adcPainelLayout = new javax.swing.GroupLayout(adcPainel);
        adcPainel.setLayout(adcPainelLayout);
        adcPainelLayout.setHorizontalGroup(
            adcPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adcPainelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adcPainelLayout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addGroup(adcPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(adcPainelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(16, 16, 16)
                        .addComponent(funcAdc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adcPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(adcPainelLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cameraAdc, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(adcPainelLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(diaAdc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(mesAdc, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(anoAdc, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(80, 80, 80))
            .addGroup(adcPainelLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(salvarBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        adcPainelLayout.setVerticalGroup(
            adcPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adcPainelLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(adcPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cameraAdc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adcPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(diaAdc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesAdc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anoAdc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(adcPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(funcAdc, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salvarBtn)
                .addGap(5, 5, 5))
        );

        getContentPane().add(adcPainel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 310));

        javax.swing.GroupLayout excPainelLayout = new javax.swing.GroupLayout(excPainel);
        excPainel.setLayout(excPainelLayout);
        excPainelLayout.setHorizontalGroup(
            excPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        excPainelLayout.setVerticalGroup(
            excPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        getContentPane().add(excPainel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 310));

        sistemMenu.setText("Sistema");

        logoutMenu.setText("Logout");
        logoutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuActionPerformed(evt);
            }
        });
        sistemMenu.add(logoutMenu);

        menuBar.add(sistemMenu);

        arquivoMenu.setText("Arquivo");

        novoArq.setText("Novo Arquivo");
        novoArq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoArqActionPerformed(evt);
            }
        });
        arquivoMenu.add(novoArq);

        verAqr.setText("Ver Arquivos");
        verAqr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verAqrActionPerformed(evt);
            }
        });
        arquivoMenu.add(verAqr);

        excluirArq.setText("Excluir Arquivo");
        excluirArq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirArqActionPerformed(evt);
            }
        });
        arquivoMenu.add(excluirArq);

        menuBar.add(arquivoMenu);

        usuarioMenu.setText("Usuário");

        addUser.setText("Adicionar Usuário");
        addUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserActionPerformed(evt);
            }
        });
        usuarioMenu.add(addUser);

        excUser.setText("Excluir Usuário");
        excUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excUserActionPerformed(evt);
            }
        });
        usuarioMenu.add(excUser);

        editUser.setText("Editar Usuário");
        editUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUserActionPerformed(evt);
            }
        });
        usuarioMenu.add(editUser);

        menuBar.add(usuarioMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Ação ao clicar no botão "Acessar"
     * Irá avaliar se o nome do usuário consta no Banco de dados,
     * após isso irá avaliar se sua senha coincide com a do respectivo usuário
     * por ultimo irá ver o tipo de usuário, para saber quais menus e opções ele terá(
     * Se ele for um usuário comum, as Funções do menu usuário estarão inativas e a opção de apagar arquivos tambem.
     * Porém se ele for um usuário master essas opções estarão ativas)
     * depois disso ira passar para a tela principal onde o usuário podera escolher no menu o que deseja fazer
     * 
     * caso o login ou senha do usuário seja incompativel o sistema o informará disso e dará a opção de voltar para a tela de login
     */
    private void acessarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acessarBtnActionPerformed
        String login = loginTxt.getText();
        String senha = senhaTxt.getText();
        ResultSet rs = db.searchByString("usuarios", "user_name", login);
        
        boolean acesso = false;
    try {
        while(rs.next()){
            if(rs.getString("user_name").equals(login)){
                if(rs.getString("user_password").equals(senha)){
                    acesso = true;
                    if(rs.getString("user_type").equals("master")){
                        usuarioMenu.setVisible(true);
                        excluirArq.setVisible(true);
                    }
                }
            }
        }
    } catch (SQLException ex) {
        Logger.getLogger(CadernoDeRegistro.class.getName()).log(Level.SEVERE, null, ex);
    }
    if(!acesso){
        negadoTxt.setVisible(true);
        loginTxt.setVisible(false);
        loginLabel.setVisible(false);
        senhaTxt.setVisible(false);
        senhaLabel.setVisible(false);
        acessarBtn.setVisible(false);
        voltarBtn.setVisible(true);
    }
    else{
        loginPainel.setVisible(false);
        menuPainel.setVisible(true);
        menuBar.setVisible(true);
        func = login;
        }
    }//GEN-LAST:event_acessarBtnActionPerformed
    /**
     * Ação de cliclar no botão voltar,
     * Este botão aparece quando o usuário digita a senho ou o login incorretamente,
     * após clilcar neste botão o usuário irá ser redirecionado para a tela de login para que coloque as inforamções corretas.
     */
    private void voltarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarBtnActionPerformed
        negadoTxt.setVisible(false);
        loginTxt.setVisible(true);
        loginLabel.setVisible(true);
        senhaTxt.setVisible(true);
        senhaLabel.setVisible(true);
        acessarBtn.setVisible(true);
        voltarBtn.setVisible(false);
        loginTxt.setText("");
        senhaTxt.setText("");
    }//GEN-LAST:event_voltarBtnActionPerformed
    /**
     * Botão de salvar arquivo, na tela de novo arquivo
     * Este botão pega as informações passada pelo o usuário e as salva no banco de dados dentro da tabela arquivo.
     */
    private void salvarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarBtnActionPerformed
        if(anoAdc.getText() != null && mesAdc.getText() != null && diaAdc.getText() != null && funcAdc.getText() != null && txtAdc.getText() != null && cameraAdc.getText() != null){
            String data = anoAdc.getText() + "-" + mesAdc.getText() + "-" + diaAdc.getText();
            Date d = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("H:m:s");
            String hora = sdf.format(d);

            String dataSql = data + " " + hora;
            db.insert("arquivo","(default,"+"'"+funcAdc.getText()+"','"+dataSql+"','"+cameraAdc.getText()+"','"+txtAdc.getText()+"');");
            verAqrActionPerformed(evt);
        }
    }//GEN-LAST:event_salvarBtnActionPerformed
    /**
     * Opção do menu para ver arquivos que constam no Banco de Dados
     * ao clicar nesta opção a tela de apresentação de arquivos recebe verdadeiro.
     * usando a variável 'i' inicializada no inicio do programa ele ira passar de id em id.
     * A passagem de Arquivo(por id) é feita ao clicar no botão 'proximo' ou 'anterior'(suas funções serão explicadas mais a baixo).
     * No final faz um teste para saber se existe um arquivo anterior, se não o botão 'anterior' desaparece.
     * O mesmo com  botão 'proximo' caso não exista um arquivo a seguir
     */
    private void verAqrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verAqrActionPerformed
        loginPainel.setVisible(false);
        menuPainel.setVisible(false);
        adcPainel.setVisible(false);
        verPainel.setVisible(true);
        proximoVer.setVisible(true);
        anteriorVer.setVisible(true);
        int cont = 0;
        ResultSet rs = null;
        rs = db.searchById("arquivo",i);
        try {
            while(rs.next()){
                idVer.setText(Integer.toString(rs.getInt("id")));
                funcVer.setText(rs.getString("funcionario"));
                dataVer.setText(rs.getString("data"));
                cameraVer.setText(rs.getString("camera"));
                txtVer.setText(rs.getNString("texto"));
            }
            rs = db.query("select * from arquivo");
            while(rs.next()){
                cont++;
            }
            if(i == 1){
                anteriorVer.setVisible(false);
            }
            if (i == cont){
                proximoVer.setVisible(false);
            }

        } catch (SQLException ex) {
             Logger.getLogger(CadernoDeRegistro.class.getName()).log(Level.SEVERE, null, ex);
        }
        
                
    }//GEN-LAST:event_verAqrActionPerformed
    /**
     * Opção do menu para criar e salvar arquivo novo.
     * Torna verdadeira a visibilidade da tela de adicionar arquivo.
     */
    private void novoArqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoArqActionPerformed

        loginPainel.setVisible(false);
        menuPainel.setVisible(false);
        adcPainel.setVisible(true);
        diaAdc.setText(null);
        mesAdc.setText(null);
        anoAdc.setText(null);
        cameraAdc.setText(null);
        txtAdc.setText(null);
        funcAdc.setText(null);
        verPainel.setVisible(false);
        funcAdc.setText(func);
    }//GEN-LAST:event_novoArqActionPerformed
    /**
     * (OPÇÃO EM DESENVOLVIMENTO)Opção do menu 'arquivo', exclusiva para o tipo de usuário master, para excluir um arquivo a partir do seu id.
     *  
     */
    private void excluirArqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirArqActionPerformed
        loginPainel.setVisible(false);
        menuPainel.setVisible(false);
        adcPainel.setVisible(false);
        verPainel.setVisible(false);
        excPainel.setVisible(true);
    }//GEN-LAST:event_excluirArqActionPerformed
    /**
     * Ação ao clicar no botão 'Anterior' na tela de visualização de arquivos.
     * Essa ação diminui um de 'i',varável usada para passar o id do arquivo que o usuário está vendo.
     * Opção fica invisivel se o arquivo for o primeiro.
     */
    private void anteriorVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorVerActionPerformed
        i -=1;
        verAqrActionPerformed(evt);
    }//GEN-LAST:event_anteriorVerActionPerformed
    /**
     * Ação ao clicar no botão 'Proximo' na tela de visualização de arquivos.
     * Essa ação acrescenta um de 'i',varável usada para passar o id do arquivo que o usuário está vendo.
     * Opção fica invisivel se o arquivo for o ultimo.
     */
    private void proximoVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximoVerActionPerformed
        i +=1;
        verAqrActionPerformed(evt);

    }//GEN-LAST:event_proximoVerActionPerformed
    /**
     * (OPÇÃO EM DESENVOLVIMENTO)Opção do menu usuário, especifico para usuários master, para adicionar novo usuário no banco de dados
     */
    private void addUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addUserActionPerformed
    /**
     * (OPÇÃO EM DESENVOLVIMENTO)Opção do menu usuário, especifico para usuários master, para excluir usuário do banco de dados
     */
    private void excUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_excUserActionPerformed
    /**
     * (OPÇÃO EM DESENVOLVIMENTO)Opção do menu usuário, especifico para usuários master, para editar usuário do banco de dados
     */
    private void editUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editUserActionPerformed
    /**
     * Opção do menu 'Sistema' para fazer o logout e voltar para o painel de menu
     */
    private void logoutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuActionPerformed
    try {
        db.Connection().close();
        db = new DAO("jdbc:mysql://localhost:3306/registro",root,password); //Realiza conexão com o banco de dados Registro, recebendo o usuario e a senha do BD como Variáveis.
    } catch (SQLException ex) {
        Logger.getLogger(CadernoDeRegistro.class.getName()).log(Level.SEVERE, null, ex);
    }
    loginTxt.setText("");
    senhaTxt.setText("");
    negadoTxt.setVisible(false);
    voltarBtn.setVisible(false);
    menuBar.setVisible(false);
    menuPainel.setVisible(false);
    adcPainel.setVisible(false);
    verPainel.setVisible(false);
    usuarioMenu.setVisible(false);
    excluirArq.setVisible(false);
    loginPainel.setVisible(true);
    }//GEN-LAST:event_logoutMenuActionPerformed


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
         //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadernoDeRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadernoDeRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadernoDeRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadernoDeRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new RunnableImpl());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acessarBtn;
    private javax.swing.JPanel adcPainel;
    private javax.swing.JMenuItem addUser;
    private javax.swing.JFormattedTextField anoAdc;
    private javax.swing.JButton anteriorVer;
    private javax.swing.JMenu arquivoMenu;
    private javax.swing.JTextField cameraAdc;
    private javax.swing.JLabel cameraVer;
    private javax.swing.JLabel dataVer;
    private javax.swing.JFormattedTextField diaAdc;
    private javax.swing.JMenuItem editUser;
    private javax.swing.JPanel excPainel;
    private javax.swing.JMenuItem excUser;
    private javax.swing.JMenuItem excluirArq;
    private javax.swing.JLabel funcAdc;
    private javax.swing.JLabel funcVer;
    private javax.swing.JLabel idVer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPanel loginPainel;
    private javax.swing.JTextField loginTxt;
    private javax.swing.JMenuItem logoutMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel menuPainel;
    private javax.swing.JFormattedTextField mesAdc;
    private javax.swing.JLabel negadoTxt;
    private javax.swing.JMenuItem novoArq;
    private javax.swing.JButton proximoVer;
    private javax.swing.JButton salvarBtn;
    private javax.swing.JLabel senhaLabel;
    private javax.swing.JPasswordField senhaTxt;
    private javax.swing.JMenu sistemMenu;
    private javax.swing.JTextArea txtAdc;
    private javax.swing.JTextArea txtVer;
    private javax.swing.JMenu usuarioMenu;
    private javax.swing.JMenuItem verAqr;
    private javax.swing.JPanel verPainel;
    private javax.swing.JButton voltarBtn;
    // End of variables declaration//GEN-END:variables

    private static class RunnableImpl implements Runnable {

        public RunnableImpl() {
        }

        public void run() {
            new CadernoDeRegistro().setVisible(true);
            
        }
    }
}
