package CadernoDeRegistro;
import DAO.DAO;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Felipe
 */
public class CadernoDeRegistro extends javax.swing.JFrame {
DAO db = new DAO("jdbc:mysql://localhost:3306/registro","root","felipe15");
String dataBase = "registro";
String func;
int i = 1;


    public CadernoDeRegistro() {
        initComponents();
        negadoTxt.setVisible(false);
        voltarBtn.setVisible(false);
        menuBar.setVisible(false);
        menuPainel.setVisible(false);
        adcPainel.setVisible(false);
        verPainel.setVisible(false);
        db.update("create table if not exists arquivo"+
                                "(id int auto_increment primary key,"+
                                "funcionario varchar(80),"+
                                "data datetime,"+
                                "camera varchar(20),"+
                                "texto mediumtext);");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        verPainel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtVer = new javax.swing.JTextArea();
        proximoVer = new javax.swing.JButton();
        anteriorVer = new javax.swing.JButton();
        funcVer = new javax.swing.JLabel();
        dataVer = new javax.swing.JLabel();
        cameraVer = new javax.swing.JLabel();
        idVer = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        loginPainel = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        loginTxt = new javax.swing.JTextField();
        senhaLabel = new javax.swing.JLabel();
        acessarBtn = new javax.swing.JButton();
        senhaTxt = new javax.swing.JPasswordField();
        negadoTxt = new javax.swing.JLabel();
        voltarBtn = new javax.swing.JButton();
        menuPainel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        adcPainel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAdc = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cameraAdc = new javax.swing.JTextField();
        salvarBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        diaAdc = new javax.swing.JFormattedTextField();
        mesAdc = new javax.swing.JFormattedTextField();
        anoAdc = new javax.swing.JFormattedTextField();
        funcAdc = new javax.swing.JLabel();
        excPainel = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        arquivoMenu = new javax.swing.JMenu();
        novoArq = new javax.swing.JMenuItem();
        verAqr = new javax.swing.JMenuItem();
        excluirArq = new javax.swing.JMenuItem();
        sairMenu = new javax.swing.JMenuItem();
        usuarioMenu = new javax.swing.JMenu();
        addUser = new javax.swing.JMenuItem();
        excUser = new javax.swing.JMenuItem();
        editUser = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.white);
        setLocation(new java.awt.Point(300, 200));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Funcionario :");

        jLabel8.setText("Dia / Hora : ");

        jLabel9.setText("Camera :");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtVer.setEditable(false);
        txtVer.setColumns(20);
        txtVer.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        txtVer.setRows(5);
        jScrollPane2.setViewportView(txtVer);

        proximoVer.setText("Proximo ->");
        proximoVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximoVerActionPerformed(evt);
            }
        });

        anteriorVer.setText("<-Anterior");
        anteriorVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorVerActionPerformed(evt);
            }
        });

        funcVer.setText("jLabel10");

        dataVer.setText("jLabel11");

        cameraVer.setText("jLabel12");

        jLabel10.setText("---------------------------------------------------------------------------------------");

        jLabel11.setText("---------------------------------------------------------------------------------------");

        javax.swing.GroupLayout verPainelLayout = new javax.swing.GroupLayout(verPainel);
        verPainel.setLayout(verPainelLayout);
        verPainelLayout.setHorizontalGroup(
            verPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verPainelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(verPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, verPainelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(idVer, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(verPainelLayout.createSequentialGroup()
                        .addGroup(verPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(verPainelLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cameraVer, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(verPainelLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(funcVer, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(verPainelLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dataVer, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 49, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(verPainelLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(anteriorVer)
                .addGap(18, 18, 18)
                .addComponent(proximoVer, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        verPainelLayout.setVerticalGroup(
            verPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verPainelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(verPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(funcVer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(verPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataVer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(3, 3, 3)
                .addGroup(verPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cameraVer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(verPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proximoVer)
                    .addComponent(anteriorVer))
                .addGap(4, 4, 4)
                .addComponent(idVer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );

        getContentPane().add(verPainel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 310));

        loginPainel.setForeground(new java.awt.Color(255, 255, 255));
        loginPainel.setInheritsPopupMenu(true);

        loginLabel.setText("Login :");

        senhaLabel.setText("Senha :");

        acessarBtn.setText("Acessar");
        acessarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acessarBtnActionPerformed(evt);
            }
        });

        negadoTxt.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        negadoTxt.setForeground(new java.awt.Color(153, 51, 0));
        negadoTxt.setText("Login/senha incorreta");

        voltarBtn.setText("Voltar");
        voltarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPainelLayout = new javax.swing.GroupLayout(loginPainel);
        loginPainel.setLayout(loginPainelLayout);
        loginPainelLayout.setHorizontalGroup(
            loginPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPainelLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(loginPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPainelLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(loginPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(voltarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acessarBtn)))
                    .addGroup(loginPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(loginPainelLayout.createSequentialGroup()
                            .addComponent(loginLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(loginTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(loginPainelLayout.createSequentialGroup()
                            .addComponent(senhaLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(loginPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(negadoTxt)
                                .addComponent(senhaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        loginPainelLayout.setVerticalGroup(
            loginPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPainelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(loginPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginLabel)
                    .addComponent(loginTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(negadoTxt)
                .addGap(13, 13, 13)
                .addGroup(loginPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhaLabel)
                    .addComponent(senhaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(acessarBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(voltarBtn)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getContentPane().add(loginPainel, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 39, 340, 250));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("Caderno de Registro");

        javax.swing.GroupLayout menuPainelLayout = new javax.swing.GroupLayout(menuPainel);
        menuPainel.setLayout(menuPainelLayout);
        menuPainelLayout.setHorizontalGroup(
            menuPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPainelLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel12)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        menuPainelLayout.setVerticalGroup(
            menuPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPainelLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel12)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        getContentPane().add(menuPainel, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 1, 420, 310));

        txtAdc.setColumns(20);
        txtAdc.setRows(5);
        jScrollPane1.setViewportView(txtAdc);

        jLabel1.setText("Camera :");

        jLabel3.setText("Dia :");

        jLabel4.setText("Funcionario :");

        salvarBtn.setText("Salvar");
        salvarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarBtnActionPerformed(evt);
            }
        });

        jLabel5.setText("/");

        jLabel6.setText("/");

        try {
            diaAdc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            mesAdc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            anoAdc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout adcPainelLayout = new javax.swing.GroupLayout(adcPainel);
        adcPainel.setLayout(adcPainelLayout);
        adcPainelLayout.setHorizontalGroup(
            adcPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adcPainelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adcPainelLayout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addGroup(adcPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(adcPainelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(16, 16, 16)
                        .addComponent(funcAdc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adcPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(adcPainelLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cameraAdc, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(adcPainelLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(diaAdc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(mesAdc, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(anoAdc, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(80, 80, 80))
            .addGroup(adcPainelLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(salvarBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        adcPainelLayout.setVerticalGroup(
            adcPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adcPainelLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(adcPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cameraAdc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adcPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(diaAdc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesAdc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anoAdc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(adcPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(funcAdc, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salvarBtn)
                .addGap(5, 5, 5))
        );

        getContentPane().add(adcPainel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 310));

        javax.swing.GroupLayout excPainelLayout = new javax.swing.GroupLayout(excPainel);
        excPainel.setLayout(excPainelLayout);
        excPainelLayout.setHorizontalGroup(
            excPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        excPainelLayout.setVerticalGroup(
            excPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        getContentPane().add(excPainel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 310));

        arquivoMenu.setText("Arquivo");

        novoArq.setText("Novo Arquivo");
        novoArq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoArqActionPerformed(evt);
            }
        });
        arquivoMenu.add(novoArq);

        verAqr.setText("Ver Arquivos");
        verAqr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verAqrActionPerformed(evt);
            }
        });
        arquivoMenu.add(verAqr);

        excluirArq.setText("Excluir Arquivo");
        excluirArq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirArqActionPerformed(evt);
            }
        });
        arquivoMenu.add(excluirArq);

        sairMenu.setText("Sair");
        sairMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairMenuActionPerformed(evt);
            }
        });
        arquivoMenu.add(sairMenu);

        menuBar.add(arquivoMenu);

        usuarioMenu.setText("Usuário");

        addUser.setText("Adicionar Usuário");
        addUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserActionPerformed(evt);
            }
        });
        usuarioMenu.add(addUser);

        excUser.setText("Excluir Usuário");
        excUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excUserActionPerformed(evt);
            }
        });
        usuarioMenu.add(excUser);

        editUser.setText("Editar Usuário");
        editUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUserActionPerformed(evt);
            }
        });
        usuarioMenu.add(editUser);

        menuBar.add(usuarioMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acessarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acessarBtnActionPerformed
        String login = loginTxt.getText();
        String senha = senhaTxt.getText();
        ResultSet rs = db.query("select * from usuarios order by id");
        
        boolean acesso = false;
    try {
        while(rs.next()){
            if(rs.getString("user_name").equals(login)){
                if(rs.getString("user_password").equals(senha)){
                    acesso = true;
                }
            }
        }
    } catch (SQLException ex) {
        Logger.getLogger(CadernoDeRegistro.class.getName()).log(Level.SEVERE, null, ex);
    }
    if(!acesso){
        negadoTxt.setVisible(true);
        loginTxt.setVisible(false);
        loginLabel.setVisible(false);
        senhaTxt.setVisible(false);
        senhaLabel.setVisible(false);
        acessarBtn.setVisible(false);
        voltarBtn.setVisible(true);
    }
    else{
        loginPainel.setVisible(false);
        menuPainel.setVisible(true);
        menuBar.setVisible(true);
        
        func = login;
        }
    }//GEN-LAST:event_acessarBtnActionPerformed

    private void voltarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarBtnActionPerformed
        negadoTxt.setVisible(false);
        loginTxt.setVisible(true);
        loginLabel.setVisible(true);
        senhaTxt.setVisible(true);
        senhaLabel.setVisible(true);
        acessarBtn.setVisible(true);
        voltarBtn.setVisible(false);
        loginTxt.setText("");
        senhaTxt.setText("");
    }//GEN-LAST:event_voltarBtnActionPerformed

    private void salvarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarBtnActionPerformed
        if(anoAdc.getText() != null && mesAdc.getText() != null && diaAdc.getText() != null && funcAdc.getText() != null && txtAdc.getText() != null && cameraAdc.getText() != null){
            String data = anoAdc.getText() + "-" + mesAdc.getText() + "-" + diaAdc.getText();
            Date d = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("H:m:s");
            String hora = sdf.format(d);

            String dataSql = data + " " + hora;
            db.insert("arquivo","(default,"+"'"+funcAdc.getText()+"','"+dataSql+"','"+cameraAdc.getText()+"','"+txtAdc.getText()+"');");
            verAqrActionPerformed(evt);
        }
    }//GEN-LAST:event_salvarBtnActionPerformed

    private void verAqrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verAqrActionPerformed
        loginPainel.setVisible(false);
        menuPainel.setVisible(false);
        adcPainel.setVisible(false);
        verPainel.setVisible(true);
        proximoVer.setVisible(true);
        anteriorVer.setVisible(true);
        ResultSet rs = null;
        rs = db.searchById("arquivo",i);
        try {
            while(rs.next()){
                idVer.setText(Integer.toString(rs.getInt("id")));
                funcVer.setText(rs.getString("funcionario"));
                dataVer.setText(rs.getString("data"));
                cameraVer.setText(rs.getString("camera"));
                txtVer.setText(rs.getNString("texto"));
            }
            if(rs.isFirst()){
                anteriorVer.setVisible(false);
            }
            if (rs.isLast()){
                proximoVer.setVisible(false);
            }
        } catch (SQLException ex) {
             Logger.getLogger(CadernoDeRegistro.class.getName()).log(Level.SEVERE, null, ex);
        }
        
                
    }//GEN-LAST:event_verAqrActionPerformed

    private void novoArqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoArqActionPerformed

        loginPainel.setVisible(false);
        menuPainel.setVisible(false);
        adcPainel.setVisible(true);
        diaAdc.setText(null);
        mesAdc.setText(null);
        anoAdc.setText(null);
        cameraAdc.setText(null);
        txtAdc.setText(null);
        funcAdc.setText(null);
        verPainel.setVisible(false);
        funcAdc.setText(func);
    }//GEN-LAST:event_novoArqActionPerformed

    private void sairMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairMenuActionPerformed
        loginPainel.setVisible(true);
        menuPainel.setVisible(false);
        adcPainel.setVisible(false);
        verPainel.setVisible(false);
        loginTxt.setText("");
        senhaTxt.setText("");
    }//GEN-LAST:event_sairMenuActionPerformed

    private void excluirArqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirArqActionPerformed
        loginPainel.setVisible(false);
        menuPainel.setVisible(false);
        adcPainel.setVisible(false);
        verPainel.setVisible(false);
        excPainel.setVisible(true);
    }//GEN-LAST:event_excluirArqActionPerformed

    private void anteriorVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorVerActionPerformed
        i -=1;
        verAqrActionPerformed(evt);
    }//GEN-LAST:event_anteriorVerActionPerformed

    private void proximoVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximoVerActionPerformed
        i +=1;
        verAqrActionPerformed(evt);

    }//GEN-LAST:event_proximoVerActionPerformed

    private void addUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addUserActionPerformed

    private void excUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_excUserActionPerformed

    private void editUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editUserActionPerformed


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

         //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadernoDeRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadernoDeRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadernoDeRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadernoDeRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadernoDeRegistro().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acessarBtn;
    private javax.swing.JPanel adcPainel;
    private javax.swing.JMenuItem addUser;
    private javax.swing.JFormattedTextField anoAdc;
    private javax.swing.JButton anteriorVer;
    private javax.swing.JMenu arquivoMenu;
    private javax.swing.JTextField cameraAdc;
    private javax.swing.JLabel cameraVer;
    private javax.swing.JLabel dataVer;
    private javax.swing.JFormattedTextField diaAdc;
    private javax.swing.JMenuItem editUser;
    private javax.swing.JPanel excPainel;
    private javax.swing.JMenuItem excUser;
    private javax.swing.JMenuItem excluirArq;
    private javax.swing.JLabel funcAdc;
    private javax.swing.JLabel funcVer;
    private javax.swing.JLabel idVer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPanel loginPainel;
    private javax.swing.JTextField loginTxt;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel menuPainel;
    private javax.swing.JFormattedTextField mesAdc;
    private javax.swing.JLabel negadoTxt;
    private javax.swing.JMenuItem novoArq;
    private javax.swing.JButton proximoVer;
    private javax.swing.JMenuItem sairMenu;
    private javax.swing.JButton salvarBtn;
    private javax.swing.JLabel senhaLabel;
    private javax.swing.JPasswordField senhaTxt;
    private javax.swing.JTextArea txtAdc;
    private javax.swing.JTextArea txtVer;
    private javax.swing.JMenu usuarioMenu;
    private javax.swing.JMenuItem verAqr;
    private javax.swing.JPanel verPainel;
    private javax.swing.JButton voltarBtn;
    // End of variables declaration//GEN-END:variables
}
